// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPO7LkRVCk-cCurPYyfR88SGDXhmf2gns',
    appId: '1:83089540633:web:d0ef07447364defe758c88',
    messagingSenderId: '83089540633',
    projectId: 'fir-notes-18dbc',
    authDomain: 'fir-notes-18dbc.firebaseapp.com',
    storageBucket: 'fir-notes-18dbc.firebasestorage.app',
    measurementId: 'G-T5P02RNY7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgqPFoleqwqBACVKqS-2qEObObNnwys4',
    appId: '1:83089540633:android:92cef05be6acf2aa758c88',
    messagingSenderId: '83089540633',
    projectId: 'fir-notes-18dbc',
    storageBucket: 'fir-notes-18dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhCO78-I43dTabTot5-Nc12ctFtympeA',
    appId: '1:83089540633:ios:c0cc5a5dc91a6d3e758c88',
    messagingSenderId: '83089540633',
    projectId: 'fir-notes-18dbc',
    storageBucket: 'fir-notes-18dbc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhCO78-I43dTabTot5-Nc12ctFtympeA',
    appId: '1:83089540633:ios:c0cc5a5dc91a6d3e758c88',
    messagingSenderId: '83089540633',
    projectId: 'fir-notes-18dbc',
    storageBucket: 'fir-notes-18dbc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPO7LkRVCk-cCurPYyfR88SGDXhmf2gns',
    appId: '1:83089540633:web:a7a33ea540778513758c88',
    messagingSenderId: '83089540633',
    projectId: 'fir-notes-18dbc',
    authDomain: 'fir-notes-18dbc.firebaseapp.com',
    storageBucket: 'fir-notes-18dbc.firebasestorage.app',
    measurementId: 'G-KJ7QZ7XGGT',
  );
}
